In [1]:
def classify_image(image):
    class_label = 'what'
    return class_label

In [2]:
classify_image('heelo')

'what'

In [6]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [2]:
import numpy as np

a = np.array([[1,1],
              [2,2],
              [3,3]])
b = np.array([[1,1,1],
              [2,2,2]])
a.dot(b)


array([[3, 3, 3],
       [6, 6, 6],
       [9, 9, 9]])

In [39]:
c = np.tile([1,2,3], (4,1))
c


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5])
c = np.reshape(a, (6,1))

a1 = np.array([1,1,1])
a2 = np.tile(a1, (3,1))
print(a2-a1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


<h1>loss functiion</h1>

In [14]:
import numpy as np

def L_i_vectorized(x, y, W):
    scores = W.dot(x)
    margins = np.maximum(0, scores - scores[y] + 1)
    margins[y] = 0
    loss_i = np.sum(margins)
    print(margins)
    return loss_i

rtn = L_i_vectorized(np.array([[1],[1]]),1, np.array([[2,2],[2,2]]))
rtn

[[1]
 [0]]


1

In [36]:
import math
e = np.array([24.5, 164, 0.18]) / np.sum([24.5, 164, 0.18])
lo = -np.log10(1)
infi = 1/8
infi

0.125

In [5]:
import numpy as np
e = np.array([[[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3]],
             ])
e.shape
e


array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [48]:

def my_gen():
    num = 1
    while num < 10:
        
        yield num
        num += 1
        if num is 2:
            print('hai')
    if num >= 10:
        yield num
        print('> 10')

a = my_gen()
for i in a:
    print(i)

1
hai
2
3
4
5
6
7
8
9
10
> 10


<h1>GENERATOR</h1>

In [25]:
gen = (i for i in range(10,20))
import itertools
# next(itertools.islice(gen, 5, None))
for i in gen:
    print(i)

10
11
12
13
14
15
16
17
18
19


<h1>L2 norm</h1>

In [24]:
import numpy as np

a = np.array([0.1,0.5,-0.3,0.8]).reshape(2,2)
b = np.array([0.2,0.4]).reshape(2,1)
product = a.dot(b)
l2_norm = np.sum(product[:,0]**2)
print('%.3f' % l2_norm)


0.116


<h1>lambda</h1>

In [40]:
f = lambda x, y: (x + y)
f(1,2)

3

In [53]:
x = {'a': 1, 'b': 2}
y = {'a': 2, 'b': 2}
print({**x, **y})

{'a': 2, 'b': 2}


<h1>babysitting training</h1>

In [2]:
import numpy as np
def init_two_layer_model(input_size, hidden_size, output_size):
    model = {}
    model['W1'] = 0.0001 * np.random.randn(input_size, hidden_size)
    model['b1'] = np.zeros(hidden_size)
    model['W2'] = 0.0001 * np.random.randn(hidden_size, output_size)
    model['b2'] = np.zeros(output_size)
    return model

# model = init_two_layer_model(32*32*3, 50, 10)
# print(model)
def softmax(x):
    e_x = np.exp(x - np.max(x, axis = 0, keepdims = True))
    prob = e_x / e_x.sum(axis = 0)
    return prob

arr = np.array([1,1,3,4]).reshape(2,2)
softmax(arr)

array([[0.11920292, 0.04742587],
       [0.88079708, 0.95257413]])

In [23]:
c = np.array([2,1,3,4,6,5,7,8,3,3,5,5,2,43,5,65,4,7]).reshape(6,3)
print(c)
y = np.array([0,1,2,2,1,0]).reshape(6,)
c[range(6), y]

[[ 2  1  3]
 [ 4  6  5]
 [ 7  8  3]
 [ 3  5  5]
 [ 2 43  5]
 [65  4  7]]


array([ 2,  6,  3,  5, 43, 65])

In [ ]:
np.random