In [3]:
import sys
print(sys.version)

3.7.2 (default, Apr 26 2019, 00:21:27) 
[GCC 8.2.1 20181127]


In [4]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


<h1>Perceptron</h1>

In [22]:
import numpy as np

In [23]:
def hardlim(x):
    return 1 if x > 0 else 0

In [80]:
x = [np.array([1,0]), np.array([1,2]), np.array([-1,1])]
y = [1,1,0]
w = np.array([1,2])
w0 = 0

In [81]:
for i in range(3):
    e = y[i] - hardlim(w.dot(x[i]) + w0)
    w = w + e*(x[i])
    w0 = w0 + e
    print('e: {}, w: {}, w0: {}'.format(e, w, w0))

e: 0, w: [1 2], w0: 0
e: 0, w: [1 2], w0: 0
e: -1, w: [2 1], w0: -1


In [82]:
for i in range(3):
    e = y[i] - hardlim(w.dot(x[i]) + w0)
    w = w + e*(x[i])
    w0 = w0 + e
    print('e: {}, w: {}, w0: {}'.format(e, w, w0))

e: 0, w: [2 1], w0: -1
e: 0, w: [2 1], w0: -1
e: 0, w: [2 1], w0: -1


<h1>LMS</h1>

In [65]:
x = np.array([[1,0], [0,1], [1,1], [1,2], [2,1], [-1,0], [-1,1], [-2,-1], [-1,-1], [-2,1]])
y = np.hstack((np.tile(np.array([0]), (5,)), np.tile(np.array([1]), (5,))))


In [67]:
x

array([[ 1,  0],
       [ 0,  1],
       [ 1,  1],
       [ 1,  2],
       [ 2,  1],
       [-1,  0],
       [-1,  1],
       [-2, -1],
       [-1, -1],
       [-2,  1]])

In [74]:
mean = np.array([np.sum(x[:,0]), np.sum(x[:, 1])]) / (x.shape[0])
x_mean = x - mean
x_mean

array([[ 1.2, -0.5],
       [ 0.2,  0.5],
       [ 1.2,  0.5],
       [ 1.2,  1.5],
       [ 2.2,  0.5],
       [-0.8, -0.5],
       [-0.8,  0.5],
       [-1.8, -1.5],
       [-0.8, -1.5],
       [-1.8,  0.5]])

In [84]:
cov_matrix = x_mean.T.dot(x_mean) / 9
print(x)
print(cov_matrix)

[array([1, 0]), array([1, 2]), array([-1,  1])]
[[1.95555556 0.66666667]
 [0.66666667 0.94444444]]


In [53]:
x.T

array([[ 1,  0,  1,  1,  2, -1, -1, -2, -1, -2],
       [ 0,  1,  1,  2,  1,  0,  1, -1, -1,  1]])

In [52]:
np.cov(x.T)

array([[1.95555556, 0.66666667],
       [0.66666667, 0.94444444]])